---
- name: init environment
  hosts: all
  gather_facts: true
  remote_user: root
  roles:
      - common

- name: install httpd and mysql
  hosts: localhost
  gather_facts: true
  remote_user: root

  roles: 
      - httpd
      - mysql-server

