---
- name: install httpd on Debian-based
  apt: pkg=apache2 state=present
  when: ansible_os_family == "Debian"
  notify:
    - start httpd
 
- name: install httpd on RedHat-based
  yum:
    pkg=httpd
    state=present
  when: ansible_os_family == "RedHat"
  notify: 
    - start httpd

- name: ensure httpd is running
  service: name={{apache}} enabled=yes state=started
